---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: formica
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: backend
        image: mreider/formica-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: BACKENDPORT
          value: "3000"
        - name: FRONTENDPORT
          value: "3001"
        - name: BACKEND
          value: <BACKEND>
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: <REDISHOST>
        - name: REDIS_PASSWORD
          value: foobar
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: formica
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: formica
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---        
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: formica
  labels: 
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379  
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend