---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: formica
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: frontend
        image: mreider/formica-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
          - name: BACKENDPORT
            value: 3000
          - name: FRONTENDPORT
            value: 3001
          - name: BACKEND
            value: <BACKENDHOST>
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: formica
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 3001