on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build and Publish images
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - uses: whoan/docker-build-with-cache-action@v5
        name: Build & push Frontend Docker image
        with:
          image_name: mreider/formica-frontend
          image_tag: ${{ steps.get_version.outputs.VERSION }},latest
          context: ./frontend
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: whoan/docker-build-with-cache-action@v5
        name: Build & push Backend Docker image
        with:
          image_name: mreider/formica-backend
          image_tag: ${{ steps.get_version.outputs.VERSION }},latest
          context: ./backend
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
